### ISSUE TITLE
Datetime format in KiteTicker

### ISSUE THREAD

**Issue by nitin-tm** [zerodhatech/pykiteconnect#34]
Currently, KiteTicker is giving last_trade_time in datetime format, Is it possible to change the python datetime object to string format?

**Comment by vividvilla** [comment]
Everywhere including connect api calls we have made datetime string to python datetime object since user anyway have to convert to make use of it. For some reason you need datetime string only then you can use [`strftime`](https://docs.python.org/3.6/library/datetime.html#datetime.datetime.strftime) method to convert.

**Comment by nitin-tm** [comment]
Thanks Vivek for the prompt reply, I wanted to analyze live data, so for storing live data I am using the Kafka stream or in-memory database, problem is that if data contains python object then we need to iterate every entry for converting datetime object to the string which takes time and may lose some data. If in place of python object there is a string then we can directly store that data, objects are nowhere followed while publishing API.
